### ISSUE TITLE
Markdown(GitHub) scope doesn't work?

### ISSUE THREAD

**Issue by bobrocke** [chuyik/brackets-snippets#44]
I have written a snippet scoped to `Markdown(GitHub)` and a test document set to `Markdown(GitHub)`.

The snippet won't trigger in that document. If I change the scope to `Any`, it then fires in that document.

What did I miss?

![tester md www grav dev brackets](https://cloud.githubusercontent.com/assets/2962426/7902092/1c9ee896-0778-11e5-86e5-b706171c047c.jpg)

![tester md www grav dev brackets](https://cloud.githubusercontent.com/assets/2962426/7902091/061fa6be-0778-11e5-8122-1d9da10fb6da.jpg)

**Comment by bobrocke** [comment]
I'm not using Emmet.

**Comment by chuyik** [comment]
Hi thanks for reporting this bug.
Workaround: please choose `Markdown` rather than `Markdown(GitHub)`.

**Comment by bobrocke** [comment]
Has this fix been released? Which version should I check for?

**Comment by chuyik** [comment]
@bobrocke Yeah it should be fixed, you could try the latest one.

**Comment by bobrocke** [comment]
I have version 1.8.1 - is that the latest that includes the fix?

**Comment by chuyik** [comment]
Yes but do you still have the same problem?

**Comment by bobrocke** [comment]
Yes, I still have the problem. A snippet scoped to Markdown(GitHub) will not fire in a file set to that, but will if the snippet is set to Markdown. I have another Markdown syntax mode, Markdown Plus, and the same thing happens.

But perhaps this is good? Maybe the snippet should be scoped for the lowest common denominator and then work in higher levels?

**Comment by chuyik** [comment]
@bobrocke Sorry for not testing well this problem, I think the snippet scoped to `Markdown` should be available to all markdown files. 
But snippet scoped to `Markdown(Github)` should be only available to the `Markdown(Github)` syntax mode.
Your thoughts?

And is there any extension for `Markdown Plus` support? I'd like to test that.

**Comment by bobrocke** [comment]
Yes, I think you're right. Snippets for Markdown should work in Markdown and anything derived from Markdown (Markdown(GitHub) or Markdown Extra, as examples). Snippets for GFM should only work in Markdown(GitHub).

Markdown Plus is my own, unpublished, mode that combines Markdown(GitHub) and YAML - often used as front matter in Markdown files.

**Comment by chuyik** [comment]
@bobrocke Cool, what's the language id of Markdown Plus? I think you should know it if you write it.

**Comment by bobrocke** [comment]
```
    LanguageManager.defineLanguage("markdown_plus", {
        name: "Markdown Plus",
        mode: "markdown_plus"
    });
```
Is that what you need?

**Comment by chuyik** [comment]
Yea~
